// Code generated by goctl. DO NOT EDIT.
package types

type LolinRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginReply struct {
	Token string `json:"token"`
}
